---
- hosts: 127.0.0.1
  become: no
  gather_facts: false
  tasks:
    - name: create a managed zone
      gcp_dns_managed_zone:
        name: example-tk
        dns_name: example.tk.
        description: example-tk
        project: "{{ lookup('env','GCP_PROJECT') }}"
        state: present
      register: managed_zone

    - name: debug
      debug: var=managed_zone

    - name: create a resource record set
      gcp_dns_resource_record_set:
        name: helloweb.example.tk.
        project: "{{ lookup('env','GCP_PROJECT') }}"
        managed_zone:
          name: "example-tk"
        type: A
        ttl: 60
        target:
        - 1.2.3.4
        state: present
